name: Stash
options:
  bundleIdPrefix: com.patrickhoy
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  Stash:
    type: application
    platform: iOS
    sources:
      - path: Stash
    info:
      path: Stash/Resources/Info.plist
      properties:
        CFBundleDisplayName: Stash
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleURLTypes:
          - CFBundleURLName: com.patrickhoy.stash
            CFBundleURLSchemes:
              - stash
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: Used to scan QR codes on storage containers.
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.patrickhoy.stash
        INFOPLIST_FILE: Stash/Resources/Info.plist
        PRODUCT_NAME: Stash
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 3JL5F3BK8A
    scheme:
      testTargets:
        - StashTests
  StashTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: StashTests
    dependencies:
      - target: Stash
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.patrickhoy.stash.tests
        GENERATE_INFOPLIST_FILE: YES
